version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.0  # Ensure PHP is available
    commands:
      - echo "Installing Composer dependencies..."
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-dev --optimize-autoloader
  pre_build:
    commands:
      - echo "Pre-build phase complete"
  build:
    commands:
      - echo "Build phase complete"
  post_build:
    commands:
      - echo "Deploying to the server..."
      # Add deployment commands like SCP, rsync, etc.

artifacts:
  files:
    - '**/*'
  base-directory: /var/www/html/Horeca-Store
