name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare SSH
        run: |
          # Create SSH directory
          mkdir -p ~/.ssh

          # Write SSH key with proper permissions
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Create SSH config to bypass strict host checking
          touch ~/.ssh/config
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Deploy to EC2
        run: |
          # Verify SSH key exists and has correct permissions
          ls -l ~/.ssh/id_ed25519
          
          # Attempt SSH connection with verbose output
          ssh -vvv -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.AWS_INSTANCE_IP }} << 'EOF'
            cd /var/www/html/Horeca-Store

            # Git configuration and pull
            sudo git config --global --add safe.directory /var/www/html/Horeca-Store
            git fetch origin main
            git reset --hard origin/main

            # Comprehensive permission fix
            sudo chown -R www-data:www-data .
            sudo chmod -R 775 storage bootstrap/cache
            sudo find . -type d -exec chmod 755 {} \;
            sudo find . -type f -exec chmod 644 {} \;

            # Ensure Laravel directories exist
            mkdir -p storage/framework/cache
            mkdir -p storage/framework/sessions
            mkdir -p storage/framework/views
            mkdir -p storage/logs
            mkdir -p bootstrap/cache

            # Set permissions for Laravel directories
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # Composer update and install
            composer install --no-interaction --prefer-dist --optimize-autoloader
            composer update square/square

            # Laravel commands
            php artisan cache:clear
            php artisan config:clear
            php artisan view:clear
            php artisan route:clear
            php artisan migrate --force
            php artisan optimize

            echo "Deployment completed successfully!"
          EOF