name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.AWS_INSTANCE_IP }} << 'EOF'
            cd /var/www/html/Horeca-Store

            # Git configuration and pull
            sudo git config --global --add safe.directory /var/www/html/Horeca-Store
            git fetch origin main
            git reset --hard origin/main

            # Comprehensive permission fix
            sudo chown -R www-data:www-data .
            sudo chmod -R 775 storage bootstrap/cache
            sudo find . -type d -exec chmod 755 {} \;
            sudo find . -type f -exec chmod 644 {} \;

            # Ensure Laravel directories exist
            mkdir -p storage/framework/cache
            mkdir -p storage/framework/sessions
            mkdir -p storage/framework/views
            mkdir -p storage/logs
            mkdir -p bootstrap/cache

            # Set permissions for Laravel directories
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # Composer update and install
            composer update square/square

            # Laravel commands
            php artisan cache:clear
            php artisan config:clear
            php artisan view:clear
            php artisan route:clear
            php artisan migrate --force
            php artisan optimize

            echo "Deployment completed successfully!"
          EOF