name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      # Step 3: Deploy changes to EC2
      - name: Deploy to EC2
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          
          # Deploy to EC2
          ssh -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.AWS_INSTANCE_IP }} << 'EOF'
            cd /var/www/html/Horeca-Store
            
            # Configure git
            sudo git config --global --add safe.directory /var/www/html/Horeca-Store
            sudo git config --global --add safe.directory '*'
            
            # Temporarily change ownership to ubuntu user
            sudo chown -R ubuntu:ubuntu .
            
            # Pull changes
            git fetch origin main
            git reset --hard origin/main
            
            # Fix permissions
            sudo chown -R www-data:www-data .
            sudo find . -type f -exec chmod 644 {} \;
            sudo find . -type d -exec chmod 755 {} \;
            
            # Set specific permissions for storage and cache
            sudo chmod -R 775 storage bootstrap/cache
            
            # Clear caches
            sudo php artisan cache:clear
            sudo php artisan config:clear
            sudo php artisan view:clear
            sudo php artisan route:clear
            
            # Run migrations
            sudo php artisan migrate --force
            
            # Optimize
            sudo php artisan optimize
            
            echo "Deployment completed successfully!"
            
            # Show latest commits
            echo "Latest commits:"
            git log -3 --oneline
          EOF

      # Step 4: Verify deployment
      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.AWS_INSTANCE_IP }} << 'EOF'
            cd /var/www/html/Horeca-Store
            echo "Application version:"
            sudo php artisan --version
            echo "Current git commit:"
            git rev-parse HEAD
          EOF