name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

          ssh -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.AWS_INSTANCE_IP }} << 'EOF'
            cd /var/www/html/Horeca-Store

            # Take full ownership of the directory
            sudo chown -R ubuntu:ubuntu .
            sudo chmod -R 755 .

            # Ensure git can operate
            sudo -u ubuntu git config --global --add safe.directory /var/www/html/Horeca-Store
            
            # Pull changes as ubuntu user
            sudo -u ubuntu git fetch origin main
            sudo -u ubuntu git reset --hard origin/main

            # Reset permissions comprehensively
            sudo chown -R www-data:ubuntu .
            sudo chmod -R 775 .

            # Ensure Laravel directories exist
            mkdir -p storage/framework/cache
            mkdir -p storage/framework/sessions
            mkdir -p storage/framework/views
            mkdir -p storage/logs
            mkdir -p bootstrap/cache

            # Set specific permissions for Laravel directories
            sudo chown -R www-data:ubuntu storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # Composer dependencies
            # composer install --no-interaction --prefer-dist --optimize-autoloader
           
          EOF
