name: Deploy Laravel Project to EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from, if not `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add EC2 to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        # SSH into EC2 and deploy the Laravel project
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          # Change to the Laravel project directory
          cd /var/www/html/Horeca-Store

          # Pull the latest changes from GitHub
          git pull origin main  # Change branch if necessary

          # Install dependencies (make sure Composer is installed)
          composer install --no-interaction --prefer-dist

          # Set the correct permissions for storage and cache
          sudo chown -R www-data:www-data /var/www/html/Horeca-Store
          sudo chmod -R 775 /var/www/html/Horeca-Store/storage /var/www/html/Horeca-Store/bootstrap/cache

          # Run database migrations (optional)
          php artisan migrate --force

          # Clear and cache the config and routes
          php artisan config:cache
          php artisan route:cache
          php artisan view:clear

          # Restart the web server (if necessary)
          sudo systemctl restart apache2  # or sudo systemctl restart nginx if you're using nginx
        EOF
